import { GridBox, LineEdit, CheckBox, Button, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {

    //Generate callback
    callback generate_password;

    //Generated password variable
    in-out property <string> password;

    //Main app window layout
    width: 480px;
    height: 240px;
    title: @tr("Password");
    icon: @image-url("./icon.png");
    background: gray;

    GridLayout {
        spacing: 20px;
        padding: 10px;
        Row {
            Text {
                height: 60px;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "Password generator";
                color: black;
                font-size: 20pt;
                font-family: "Arial";
            }
        }
        Row {
            generated := LineEdit {
                height: 60px;
                placeholder-text: "Password";
                text: password;
            }
            Button {
                height: 60px;
                text: "Copy";
                primary: true;
                clicked => {
                    generated.select-all(); //Select password text
                    generated.copy(); //Copy password to clipboard
                }
            }
        }
        Row {
            Button {
                text: "Generate";
                primary: true;
                height: 60px;
                clicked => {
                    generate_password();
                }
            }
        }
    }
}