import { GridBox, LineEdit, CheckBox, Button, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {

    //Generate callback
    callback generate_password;
    callback lowercase_password;
    callback number_password;
    callback special_password;

    //Generated password variable
    in-out property <string> password;
    in-out property <bool> lower;
    in-out property <bool> num;
    in-out property <bool> spec;

    //Main app window layout
    width: 480px;
    height: 480px;
    title: @tr("Password generator");
    icon: @image-url("./icon.png");
    background: grey;

    GridLayout {
        spacing: 20px;
        padding: 10px;
        Row {
            Text {
                height: 60px;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "Password generator";
                color: darkgrey;
                font-size: 20pt;
                font-family: "Arial";
                colspan: 2;
            }
        }
        Row {
            generated := LineEdit {
                height: 60px;
                width: 60%;
                placeholder-text: "Password";
                text: password;
            }
            Button {
                height: 60px;
                width: 30%;
                text: "Copy";
                primary: true;
                clicked => {
                    generated.select-all(); //Select password text
                    generated.copy(); //Copy password to clipboard
                }
            }
        }
        Row {
            Button {
                text: "Generate";
                primary: true;
                height: 60px;
                colspan: 2;
                clicked => {
                    generate_password();
                }
            }
        }
        Row {
            Text {
                text: "Password length: 16";
                height: 30px;
                font-size: 14px;
                font-weight: 100;
            }
        }
        Row {
            CheckBox {
                text: "Uppercase";
                checked: true;
                toggled => {
                    self.checked = true;
                }
            }
        }
        Row {
            CheckBox {
                text: "Lowercase";
                checked: false;
                toggled => {
                    lowercase_password();
                }
            }
        }
        Row {
            CheckBox {
                text: "Numbers";
                checked: false;
                toggled => {
                    number_password();
                }
            }
        }
        Row {
            CheckBox {
                text: "Special characters";
                checked: false;
                toggled => {
                    special_password();
                }
            }
        }
    }
}